---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins-dev
  namespace: clim8
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: jenkins-dev
  chart:
    git: https://github.com/seanmcguigan/deployments.git
    path: charts/jenkins
    ref: development
  values:
    persistence:
      enabled: false
    master:
      image: seanmcguigan/jenkins
<<<<<<< HEAD
      tag: dev-12345
=======
      tag: dev-11745
>>>>>>> 036defdfd11265fc2291e46b828b59ba4c09bf1f
      # pullSecret: gpr-docker-pull
      # pullPolicy: IfNotPresent
      replicaCount: 1
