apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins-dev
  namespace: clim8
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: jenkins-dev
  chart:
    git: git@github.com:seanmcguigan/deployments.git
    path: charts/jenkins
    ref: development
  values:
    image:
      repository: seanmcguigan/jenkins
      tag: dev-12345
     # pullSecret: gpr-docker-pull
     # pullPolicy: IfNotPresent
    replicaCount: 1