---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: poker-dev
  namespace: clim8
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: poker-dev
  chart:
    git: https://github.com/seanmcguigan/deployments.git
    path: charts/poker
    ref: development
  values:
    replicaCount: 0
    image:
      repository: seanmcguigan/poker
      tag: dev-0ioee
    containerPort: 3000
    livenessProbe:
      httpGet:
        path: /lobby-data
    readinessProbe:
      httpGet:
        path: /lobby-data
    serviceAccount:
      create: true
    service:
      type: ClusterIP
      port: 80
      targetPort: 3000
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50
